package com.example.download

import android.app.DownloadManager
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.util.Base64
import android.webkit.CookieManager
import android.webkit.MimeTypeMap
import android.webkit.URLUtil
import android.widget.Toast
import androidx.core.app.NotificationCompat
import androidx.core.content.FileProvider
import com.example.R
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Robust handler for all WebView file downloads:
 * 1. Standard HTTP/HTTPS with Content-Disposition or download links via Android DownloadManager
 * 2. Blob URLs (blob:https://...) and Data URIs (data:application/pdf;base64,...) generated by JavaScript
 * 3. File saving to public user-accessible Downloads folder
 * 4. Android system download notifications and intent-to-view
 */
object DownloadHandler {

    private const val DOWNLOAD_CHANNEL_ID = "bandhan_downloads_channel"
    private const val DOWNLOAD_CHANNEL_NAME = "Bandhan Downloads"

    /**
     * Handles standard HTTP/HTTPS download requests triggered by WebView.
     */
    fun handleHttpDownload(
        context: Context,
        url: String,
        userAgent: String?,
        contentDisposition: String?,
        mimeType: String?
    ) {
        try {
            if (url.startsWith("blob:", ignoreCase = true) || url.startsWith("data:", ignoreCase = true)) {
                // Handled via Blob/Data URI handler
                return
            }

            val guessedMime = resolveMimeType(url, mimeType, contentDisposition)
            val fileName = resolveFileName(url, contentDisposition, guessedMime)

            val downloadManager = context.getSystemService(Context.DOWNLOAD_SERVICE) as? DownloadManager
            if (downloadManager == null) {
                Toast.makeText(context, "ডাউনলোড ম্যানেজার পাওয়া যায়নি", Toast.LENGTH_SHORT).show()
                return
            }

            val request = DownloadManager.Request(Uri.parse(url)).apply {
                setMimeType(guessedMime)

                // Attach cookies for authenticated downloads (e.g., statements behind login)
                val cookies = CookieManager.getInstance().getCookie(url)
                if (!cookies.isNullOrBlank()) {
                    addRequestHeader("Cookie", cookies)
                }

                if (!userAgent.isNullOrBlank()) {
                    addRequestHeader("User-Agent", userAgent)
                }
                addRequestHeader("Accept", "*/*")
                addRequestHeader("Referer", "https://bandhan17.website/")

                setTitle(fileName)
                setDescription("বন্ধন'১৭ স্টেটমেন্ট ও ফাইল ডাউনলোড হচ্ছে...")
                setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED)
                setAllowedOverMetered(true)
                setAllowedOverRoaming(true)

                // Save directly to user-accessible Downloads directory
                setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS, fileName)
            }

            downloadManager.enqueue(request)
            Toast.makeText(context, "ডাউনলোড শুরু হয়েছে: $fileName", Toast.LENGTH_SHORT).show()
        } catch (e: Exception) {
            Toast.makeText(context, "ডাউনলোড শুরু করতে ব্যর্থ: ${e.localizedMessage ?: "Unknown error"}", Toast.LENGTH_SHORT).show()
        }
    }

    /**
     * Saves Base64 data (from blob: or data: URIs) directly to user's Public Downloads folder.
     */
    fun saveBase64Download(
        context: Context,
        base64Data: String,
        suggestedFileName: String?,
        mimeType: String?
    ) {
        CoroutineScope(Dispatchers.IO).launch {
            try {
                // Strip data URL prefixes like "data:application/pdf;base64,"
                val cleanBase64 = if (base64Data.contains(",")) {
                    base64Data.substringAfter(",")
                } else {
                    base64Data
                }

                val bytes = Base64.decode(cleanBase64, Base64.DEFAULT)
                if (bytes == null || bytes.isEmpty()) {
                    withContext(Dispatchers.Main) {
                        Toast.makeText(context, "ডাউনলোড করা ফাইল খালি", Toast.LENGTH_SHORT).show()
                    }
                    return@launch
                }

                val resolvedMime = if (!mimeType.isNullOrBlank() && mimeType != "application/octet-stream") {
                    mimeType
                } else if (base64Data.startsWith("data:")) {
                    base64Data.substringAfter("data:").substringBefore(";")
                } else {
                    "application/pdf"
                }

                val fileName = resolveBlobFileName(suggestedFileName, resolvedMime)

                var savedFileUri: Uri? = null
                var savedFile: File? = null

                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                    // Modern Android Scoped Storage using MediaStore.Downloads
                    val contentValues = ContentValues().apply {
                        put(MediaStore.Downloads.DISPLAY_NAME, fileName)
                        put(MediaStore.Downloads.MIME_TYPE, resolvedMime)
                        put(MediaStore.Downloads.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
                        put(MediaStore.Downloads.IS_PENDING, 1)
                    }

                    val resolver = context.contentResolver
                    val uri = resolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)

                    if (uri != null) {
                        resolver.openOutputStream(uri)?.use { os ->
                            os.write(bytes)
                            os.flush()
                        }
                        contentValues.clear()
                        contentValues.put(MediaStore.Downloads.IS_PENDING, 0)
                        resolver.update(uri, contentValues, null, null)
                        savedFileUri = uri
                    }
                } else {
                    // Legacy Android (Android 9 and below)
                    val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
                    downloadsDir.mkdirs()
                    val targetFile = getUniqueFile(downloadsDir, fileName)
                    FileOutputStream(targetFile).use { fos ->
                        fos.write(bytes)
                        fos.flush()
                    }
                    savedFile = targetFile
                    savedFileUri = Uri.fromFile(targetFile)

                    // Inform DownloadManager so file is visible in system Downloads UI
                    val downloadManager = context.getSystemService(Context.DOWNLOAD_SERVICE) as? DownloadManager
                    downloadManager?.addCompletedDownload(
                        targetFile.name,
                        "বন্ধন'১৭ স্টেটমেন্ট",
                        true,
                        resolvedMime,
                        targetFile.absolutePath,
                        targetFile.length(),
                        true
                    )
                }

                withContext(Dispatchers.Main) {
                    Toast.makeText(context, "ডাউনলোড সম্পন্ন হয়েছে: $fileName", Toast.LENGTH_LONG).show()
                    showDownloadNotification(context, fileName, resolvedMime, savedFileUri, savedFile)
                }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    Toast.makeText(context, "ডাউনলোড সংরক্ষণ ব্যর্থ: ${e.localizedMessage ?: "Unknown error"}", Toast.LENGTH_SHORT).show()
                }
            }
        }
    }

    /**
     * Resolves an accurate, clean filename for downloaded files.
     */
    fun resolveFileName(url: String, contentDisposition: String?, mimeType: String?): String {
        // 1. Try extracting filename from Content-Disposition header
        if (!contentDisposition.isNullOrBlank()) {
            val filenamePattern = Regex("""filename\*?=(?:UTF-8'')?["']?([^"';]+)["']?""", RegexOption.IGNORE_CASE)
            val match = filenamePattern.find(contentDisposition)
            if (match != null) {
                val rawName = match.groupValues[1].trim()
                if (rawName.isNotBlank()) {
                    return sanitizeFileName(rawName)
                }
            }
        }

        // 2. URLUtil guess (with safe fallback)
        try {
            val guessed = URLUtil.guessFileName(url, contentDisposition, mimeType)
            if (!guessed.isNullOrBlank() && !guessed.equals("downloadfile.bin", ignoreCase = true)) {
                return sanitizeFileName(guessed)
            }
        } catch (_: Throwable) {
            // Fallback for unmocked unit test / JVM environments
        }

        // 3. Fallback to timestamped statement name
        val timeStamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
        val ext = getExtensionForMime(mimeType) ?: "pdf"
        return "Bandhan17_Statement_$timeStamp.$ext"
    }

    private fun resolveBlobFileName(suggestedName: String?, mimeType: String?): String {
        if (!suggestedName.isNullOrBlank() && suggestedName != "download" && suggestedName != "unknown") {
            val sanitized = sanitizeFileName(suggestedName)
            if (sanitized.contains(".")) return sanitized
            val ext = getExtensionForMime(mimeType) ?: "pdf"
            return "$sanitized.$ext"
        }

        val timeStamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
        val ext = getExtensionForMime(mimeType) ?: "pdf"
        return "Bandhan17_Statement_$timeStamp.$ext"
    }

    private fun resolveMimeType(url: String, mimeType: String?, contentDisposition: String?): String {
        if (!mimeType.isNullOrBlank() && mimeType != "application/octet-stream" && mimeType != "*/*") {
            return mimeType
        }

        try {
            val fileExtension = MimeTypeMap.getFileExtensionFromUrl(url)
            if (!fileExtension.isNullOrBlank()) {
                val typeFromExt = MimeTypeMap.getSingleton().getMimeTypeFromExtension(fileExtension.lowercase())
                if (!typeFromExt.isNullOrBlank()) {
                    return typeFromExt
                }
            }
        } catch (_: Throwable) {
            // Fallback
        }

        if (url.endsWith(".pdf", ignoreCase = true) || contentDisposition?.contains(".pdf", ignoreCase = true) == true) {
            return "application/pdf"
        }
        if (url.endsWith(".xlsx", ignoreCase = true) || contentDisposition?.contains(".xlsx", ignoreCase = true) == true) {
            return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        }
        if (url.endsWith(".csv", ignoreCase = true) || contentDisposition?.contains(".csv", ignoreCase = true) == true) {
            return "text/csv"
        }

        return "application/octet-stream"
    }

    private fun getExtensionForMime(mimeType: String?): String? {
        if (mimeType.isNullOrBlank()) return null
        return when (mimeType.lowercase()) {
            "application/pdf" -> "pdf"
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" -> "xlsx"
            "application/vnd.ms-excel" -> "xls"
            "text/csv" -> "csv"
            "text/plain" -> "txt"
            "image/jpeg", "image/jpg" -> "jpg"
            "image/png" -> "png"
            "application/zip" -> "zip"
            else -> try {
                MimeTypeMap.getSingleton().getExtensionFromMimeType(mimeType)
            } catch (_: Throwable) {
                null
            }
        }
    }

    private fun sanitizeFileName(name: String): String {
        return name.replace(Regex("[\\\\/:*?\"<>|]"), "_").trim()
    }

    private fun getUniqueFile(dir: File, fileName: String): File {
        var file = File(dir, fileName)
        if (!file.exists()) return file

        val nameWithoutExt = fileName.substringBeforeLast(".")
        val ext = fileName.substringAfterLast(".", "")
        val extSuffix = if (ext.isNotBlank()) ".$ext" else ""

        var counter = 1
        while (file.exists()) {
            file = File(dir, "$nameWithoutExt ($counter)$extSuffix")
            counter++
        }
        return file
    }

    private fun showDownloadNotification(
        context: Context,
        fileName: String,
        mimeType: String,
        fileUri: Uri?,
        file: File?
    ) {
        try {
            val notificationManager = context.getSystemService(Context.NOTIFICATION_SERVICE) as? NotificationManager
                ?: return

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                val channel = NotificationChannel(
                    DOWNLOAD_CHANNEL_ID,
                    DOWNLOAD_CHANNEL_NAME,
                    NotificationManager.IMPORTANCE_DEFAULT
                ).apply {
                    description = "Notifications for downloaded statements and files"
                }
                notificationManager.createNotificationChannel(channel)
            }

            // Create open intent
            val viewIntent = Intent(Intent.ACTION_VIEW).apply {
                if (file != null) {
                    val contentUri = FileProvider.getUriForFile(
                        context,
                        "${context.packageName}.fileprovider",
                        file
                    )
                    setDataAndType(contentUri, mimeType)
                } else if (fileUri != null) {
                    setDataAndType(fileUri, mimeType)
                }
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }

            val pendingIntent = PendingIntent.getActivity(
                context,
                fileName.hashCode(),
                viewIntent,
                PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
            )

            val notification = NotificationCompat.Builder(context, DOWNLOAD_CHANNEL_ID)
                .setSmallIcon(android.R.drawable.stat_sys_download_done)
                .setContentTitle("ডাউনলোড সম্পন্ন হয়েছে")
                .setContentText(fileName)
                .setAutoCancel(true)
                .setContentIntent(pendingIntent)
                .setPriority(NotificationCompat.PRIORITY_DEFAULT)
                .build()

            notificationManager.notify(fileName.hashCode(), notification)
        } catch (_: Exception) {
            // Notification is secondary; toast already informs user
        }
    }
}
